
import postgres from "npm:postgres@3.4.7";

const db = postgres(Deno.env.get("SUPABASE_DB_URL")!, { max: 1, prepare: false });
const CORS = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
  "Access-Control-Allow-Methods": "POST, OPTIONS",
  "Content-Type": "application/json; charset=utf-8"
};
const ROLE_PERMS = {
  FULL_ADMIN:["*"], MATCHDAY:["match","read"], VOTING:["voting","read"],
  SUBS:["subs","read"], READ_ONLY:["read"], CUSTOM:[]
};
const norm=(v)=>String(v??"").trim();
const low=(v)=>norm(v).toLowerCase();
const bool=(v)=>v===true||low(v)==="true";
const num=(v,d=0)=>Number.isFinite(Number(v))?Number(v):d;
const int=(v,d=0)=>Number.isFinite(Number(v))?Math.trunc(Number(v)):d;
const q=(text,params=[])=>db.unsafe(text,params);
function out(result){return new Response(JSON.stringify({ok:true,result}),{headers:CORS});}
function fail(message,status=400){return new Response(JSON.stringify({ok:false,error:message}),{status,headers:CORS});}
function dateText(v){if(!v)return"";const d=new Date(v);if(Number.isNaN(d.getTime()))return String(v);return new Intl.DateTimeFormat("en-GB",{timeZone:"Europe/London",day:"2-digit",month:"2-digit",year:"numeric"}).format(d);}
function timeText(v){if(!v)return"";if(typeof v==="string"&&/^\d{2}:\d{2}/.test(v))return v.slice(0,5);const d=new Date(v);if(Number.isNaN(d.getTime()))return String(v);return new Intl.DateTimeFormat("en-GB",{timeZone:"Europe/London",hour:"2-digit",minute:"2-digit",hour12:false}).format(d);}
async function setting(name){const r=await q("select value from perranporth.settings where setting=$1 limit 1",[name]);return r.length?r[0].value:"";}
async function hash(s){const b=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(s));return Array.from(new Uint8Array(b)).map(x=>x.toString(16).padStart(2,"0")).join("");}
function custom(v){if(Array.isArray(v))return v.map(String);const s=norm(v);if(!s)return[];try{const j=JSON.parse(s);if(Array.isArray(j))return j.map(String);}catch{}return s.split(",").map(x=>x.trim()).filter(Boolean);}
async function createSession(pin){
  const p=norm(pin); if(!p)throw new Error("Incorrect PIN.");
  let source="",uid=null,pv=1;
  const app=norm(await setting("App PIN")),tmp=norm(await setting("Temporary Management PIN"));
  if(app&&p===app)source="MAIN"; else if(tmp&&p===tmp)source="TEMP";
  else{
    const users=await q("select id,pin_hash,pin_version from perranporth.management_access where active=true and coalesce(pin_hash,'')<>''");
    for(const u of users){if(await hash(String(u.id)+"|"+p)===String(u.pin_hash)){source="USER";uid=String(u.id);pv=int(u.pin_version,1);break;}}
  }
  if(!source)throw new Error("Incorrect PIN.");
  const token=crypto.randomUUID()+"-"+crypto.randomUUID(),exp=new Date(Date.now()+86400000);
  await q("insert into perranporth.admin_sessions(token,user_id,source,pin_version,expires_at) values($1,$2,$3,$4,$5)",[token,uid,source,pv,exp]);
  return {token,expiresAt:exp.getTime()};
}
async function ctx(token){
  const t=norm(token); if(!t)return null;
  await q("delete from perranporth.admin_sessions where expires_at<=now()");
  const r=await q("select user_id,source,pin_version from perranporth.admin_sessions where token=$1 and expires_at>now() limit 1",[t]);
  if(!r.length)return null; const s=r[0];
  if(s.source==="MAIN"||s.source==="TEMP")return{id:s.source,name:s.source==="MAIN"?"Main Admin":"Temporary Admin",role:"FULL_ADMIN",permissions:["*"]};
  const u=await q("select id,name,role,custom_access,pin_version,active from perranporth.management_access where id=$1 limit 1",[s.user_id]);
  if(!u.length||!u[0].active||int(u[0].pin_version,1)!==int(s.pin_version,1)){await q("delete from perranporth.admin_sessions where token=$1",[t]);return null;}
  const role=norm(u[0].role)||"READ_ONLY";return{id:String(u[0].id),name:norm(u[0].name),role,permissions:role==="CUSTOM"?custom(u[0].custom_access):(ROLE_PERMS[role]||[])};
}
async function auth(token,perm="match"){const c=await ctx(token);if(!c)throw new Error("Admin session expired. Please enter the PIN again.");if(!(c.permissions.includes("*")||c.permissions.includes(perm)))throw new Error("You do not have access to this area.");return c;}
function matchObj(r){return{matchId:String(r.match_id||""),date:dateText(r.match_date),opponent:norm(r.opponent),venue:norm(r.venue),competition:norm(r.competition),kickoff:timeText(r.kickoff),status:norm(r.status),ourScore:r.our_score==null?"":Number(r.our_score),oppScore:r.opp_score==null?"":Number(r.opp_score),formation:norm(r.formation),captain:norm(r.captain),notes:norm(r.notes),include:r.include!==false,source:norm(r.source),calendarKey:norm(r.calendar_key),ground:norm(r.ground)};}
async function matchRow(id){const r=await q("select * from perranporth.matches where match_id=$1 limit 1",[id]);if(!r.length)throw new Error("Match not found.");return r[0];}
async function matches(includeCompleted=true){const r=await q("select * from perranporth.matches order by match_date asc nulls last,kickoff asc nulls last,source_row asc");return r.map(matchObj).filter(m=>m.matchId&&m.include&&(includeCompleted||m.status!=="Completed")&&low(m.source)!=="trial"&&!/pre[- ]?season/i.test(m.calendarKey+" "+m.notes)&&!(low(m.source)==="manual"&&/^(test|testing|trial)\b/i.test(m.opponent)));}
async function players(activeOnly=true){const r=await q("select * from perranporth.players order by player");return r.filter(x=>!activeOnly||x.active).map(x=>({name:norm(x.player),active:!!x.active,position:norm(x.default_position),shirtNo:x.shirt_no??"",goalkeeper:!!x.goalkeeper,notes:norm(x.notes),alias:norm(x.voting_alias),dateOfBirth:x.date_of_birth?String(x.date_of_birth):""})).filter(x=>x.name);}
async function events(id){const r=await q("select * from perranporth.events where match_id=$1 order by minute asc,event_timestamp asc nulls last,id asc",[id]);return r.map(x=>({eventId:String(x.event_id),matchId:String(x.match_id),minute:Number(x.minute||0),type:norm(x.event_type),team:norm(x.team),player:norm(x.player),secondaryPlayer:norm(x.secondary_player),goalType:norm(x.goal_type),touches:x.touches??"",zone:norm(x.goal_zone),originZone:norm(x.assist_zone),cardReason:norm(x.card_reason),notes:norm(x.notes),timestamp:x.event_timestamp?new Date(x.event_timestamp).toLocaleString("en-GB",{timeZone:"Europe/London"}):""}));}
function score(ev){let ours=0,opp=0;for(const e of ev){if(e.type==="Goal"&&e.team!=="Opposition")ours++;if(e.type==="Conceded Goal"||(e.type==="Goal"&&e.team==="Opposition"))opp++;}return{ours,opp};}
async function squad(id){const r=await q("select * from perranporth.player_match_data where match_id=$1 order by id",[id]);return r.map(x=>({player:norm(x.player),status:norm(x.squad_status),starter:!!x.starter,position:norm(x.starting_position),shirtNo:x.shirt_no??"",minuteOn:x.minute_on??"",minuteOff:x.minute_off??"",minutesPlayed:Number(x.minutes_played||0),goals:int(x.goals),assists:int(x.assists),yellows:int(x.yellow_cards),reds:int(x.red_cards),notes:norm(x.notes)}));}
async function lineup(id){const m=await matchRow(id),r=await q("select * from perranporth.lineup_positions where match_id=$1 order by sort_order,id",[id]);return{matchId:id,formation:(r.length?norm(r[0].formation):"")||norm(m.formation)||"Custom",positions:r.filter(x=>x.player&&(x.area==="Pitch"||x.area==="Bench")).map(x=>({player:norm(x.player),area:norm(x.area),x:Number(x.x||0),y:Number(x.y||0),order:int(x.sort_order)}))};}
function defClock(id){return{matchId:id,startedAt:null,baseSeconds:0,runningSince:null,onBreak:false,half:1,firstHalfAddedMinutes:0,finishedAt:null,updatedAt:Date.now()};}
async function rawClock(id){const r=await q("select * from perranporth.match_clocks where match_id=$1 limit 1",[id]);if(!r.length)return defClock(id);const x=r[0];return{matchId:id,startedAt:x.started_at?Number(x.started_at):null,baseSeconds:int(x.base_seconds),runningSince:x.running_since?Number(x.running_since):null,onBreak:!!x.on_break,half:int(x.half,1),firstHalfAddedMinutes:int(x.first_half_added_minutes),finishedAt:x.finished_at?Number(x.finished_at):null,updatedAt:Number(x.updated_at||0)};}
function elapsed(c,n=Date.now()){return Math.max(0,int(c.baseSeconds)+(c.runningSince?Math.floor((n-Number(c.runningSince))/1000):0));}
function pubClock(c){const n=Date.now();return{matchId:c.matchId,started:!!c.startedAt,startedAt:c.startedAt||null,startedAtText:c.startedAt?timeText(new Date(Number(c.startedAt))):"",elapsedSeconds:elapsed(c,n),running:!!c.runningSince,onBreak:!!c.onBreak,half:int(c.half,1),firstHalfAddedMinutes:int(c.firstHalfAddedMinutes),finishedAt:c.finishedAt||null,finishedAtText:c.finishedAt?timeText(new Date(Number(c.finishedAt))):"",serverNow:n};}
async function writeClock(c){c.updatedAt=Date.now();await q("insert into perranporth.match_clocks(match_id,started_at,base_seconds,running_since,on_break,half,first_half_added_minutes,finished_at,updated_at) values($1,$2,$3,$4,$5,$6,$7,$8,$9) on conflict(match_id) do update set started_at=excluded.started_at,base_seconds=excluded.base_seconds,running_since=excluded.running_since,on_break=excluded.on_break,half=excluded.half,first_half_added_minutes=excluded.first_half_added_minutes,finished_at=excluded.finished_at,updated_at=excluded.updated_at",[c.matchId,c.startedAt,int(c.baseSeconds),c.runningSince,!!c.onBreak,int(c.half,1),int(c.firstHalfAddedMinutes),c.finishedAt,c.updatedAt]);return c;}
async function clock(id){return pubClock(await rawClock(id));}
async function summary(id){const m=await matchRow(id),ev=await events(id),sc=score(ev);if(Number(m.our_score??0)!==sc.ours||Number(m.opp_score??0)!==sc.opp){await q("update perranporth.matches set our_score=$1,opp_score=$2 where match_id=$3",[sc.ours,sc.opp,id]);m.our_score=sc.ours;m.opp_score=sc.opp;}return{match:matchObj(m),events:ev,squad:await squad(id),clock:await clock(id)};}
async function notDone(id){const m=await matchRow(id);if(m.status==="Completed")throw new Error("This match is already finished.");return m;}
async function validEvent(e){if(!e||!e.matchId||!e.eventType)throw new Error("Incomplete event.");if(!Number.isFinite(Number(e.minute))||Number(e.minute)<=0)throw new Error("Enter a valid match minute.");const names=new Set((await players(true)).map(x=>x.name));if(e.eventType==="Goal"){if(!e.player||!names.has(e.player))throw new Error("Select an active player.");if(e.secondaryPlayer){if(!names.has(e.secondaryPlayer))throw new Error("Select an active assist player.");if(e.secondaryPlayer===e.player)throw new Error("The scorer and assist player cannot be the same.");}}if(e.eventType==="Yellow Card"||e.eventType==="Red Card"){if(!e.player||!names.has(e.player))throw new Error("Select the player who received the card.");}if(e.eventType==="Substitution"){if(!e.player||!e.secondaryPlayer)throw new Error("Select both the player off and the player on.");if(e.player===e.secondaryPlayer)throw new Error("The player off and player on cannot be the same.");if(!names.has(e.player)||!names.has(e.secondaryPlayer))throw new Error("Select active players for the substitution.");}}
async function refreshStats(id){const ev=await events(id),rows=await q("select id,player from perranporth.player_match_data where match_id=$1",[id]);for(const r of rows){const p=String(r.player),g=ev.filter(e=>e.type==="Goal"&&e.player===p&&e.team!=="Opposition").length,a=ev.filter(e=>e.type==="Goal"&&e.secondaryPlayer===p&&e.team!=="Opposition").length,y=ev.filter(e=>e.type==="Yellow Card"&&e.player===p).length,rd=ev.filter(e=>e.type==="Red Card"&&e.player===p).length;await q("update perranporth.player_match_data set goals=$1,assists=$2,yellow_cards=$3,red_cards=$4 where id=$5",[g,a,y,rd,r.id]);}}
function minute(v){const n=Number(v||0);if(!Number.isFinite(n))return 0;const b=Math.floor(n),a=Math.round((n-b)*100);if(a>0&&(b===45||b===90))return b;return Math.max(0,Math.min(90,b));}
async function recalc(id,snap){const rows=await q("select * from perranporth.player_match_data where match_id=$1 order by id",[id]);if(!rows.length)return;const ev=await events(id),end=snap&&snap.started?(int(snap.half,1)===1?Math.max(0,Math.min(45,Math.ceil(num(snap.elapsedSeconds)/60))):90):90,ord=[...ev].sort((a,b)=>minute(a.minute)-minute(b.minute));for(const r of rows){const p=String(r.player),starter=!!r.starter;let active=starter,on=starter?0:null,first=starter?0:null,off=null,mins=0;for(const e of ord){const m=minute(e.minute);if(e.type==="Substitution"){if(e.player===p&&active){mins+=Math.max(0,m-on);active=false;on=null;off=m;}if(e.secondaryPlayer===p&&!active){active=true;on=m;if(first===null)first=m;}}if(e.type==="Red Card"&&e.player===p&&active){mins+=Math.max(0,m-on);active=false;on=null;off=m;}}if(active&&on!==null)mins+=Math.max(0,end-on);const g=ev.filter(e=>e.type==="Goal"&&e.player===p&&e.team!=="Opposition").length,a=ev.filter(e=>e.type==="Goal"&&e.secondaryPlayer===p&&e.team!=="Opposition").length,y=ev.filter(e=>e.type==="Yellow Card"&&e.player===p).length,rd=ev.filter(e=>e.type==="Red Card"&&e.player===p).length;await q("update perranporth.player_match_data set minute_on=$1,minute_off=$2,minutes_played=$3,goals=$4,assists=$5,yellow_cards=$6,red_cards=$7 where id=$8",[first,off,mins,g,a,y,rd,r.id]);}}
async function saveSquad(id,list){const m=await matchRow(id);if(m.status==="Live")throw new Error("The match is live. Edit the squad before kickoff or after full time.");await db.begin(async tx=>{await tx.unsafe("delete from perranporth.player_match_data where match_id=$1",[id]);for(const p of list||[]){const st=p.status==="Starter";await tx.unsafe("insert into perranporth.player_match_data(match_id,player,squad_status,starter,starting_position,shirt_no,minute_on,minutes_played,goals,assists,yellow_cards,red_cards,notes,raw_data) values($1,$2,$3,$4,$5,$6,$7,0,0,0,0,0,'','{}'::jsonb)",[id,norm(p.player),norm(p.status),st,norm(p.position),norm(p.shirtNo),st?0:null]);}});if(m.status==="Completed")await recalc(id,await clock(id));return summary(id);}
async function saveLineup(id,payload){const m=await matchRow(id),active=new Set((await players(true)).map(x=>x.name)),seen=new Set(),formation=norm(payload?.formation)||"Custom";const ps=(payload?.positions||[]).map((p,i)=>({player:norm(p.player),area:norm(p.area),x:num(p.x),y:num(p.y),order:int(p.order,i+1)})).filter(p=>{if(!p.player||seen.has(p.player)||!active.has(p.player)||(p.area!=="Pitch"&&p.area!=="Bench"))return false;seen.add(p.player);return true;});await db.begin(async tx=>{await tx.unsafe("delete from perranporth.lineup_positions where match_id=$1",[id]);for(const p of ps)await tx.unsafe("insert into perranporth.lineup_positions(match_id,player,area,x,y,sort_order,formation,updated_at,raw_data) values($1,$2,$3,$4,$5,$6,$7,now(),'{}'::jsonb)",[id,p.player,p.area,p.area==="Pitch"?Math.max(0,Math.min(100,p.x)):null,p.area==="Pitch"?Math.max(0,Math.min(100,p.y)):null,p.order,formation]);});if(m.status!=="Live")await saveSquad(id,ps.map(p=>({player:p.player,status:p.area==="Pitch"?"Starter":"Sub",position:"",shirtNo:""})));if(formation!=="Custom")await q("update perranporth.matches set formation=$1 where match_id=$2",[formation,id]);return lineup(id);}
async function starting(id,payload){const m=await matchRow(id);if(m.status==="Completed")throw new Error("The match is already finished.");const ps=Array.isArray(payload?.positions)?payload.positions:[],pitch=ps.filter(p=>p?.area==="Pitch"&&p.player).map(p=>norm(p.player)),bench=ps.filter(p=>p?.area==="Bench"&&p.player).map(p=>norm(p.player)),up=[...new Set(pitch)],ub=[...new Set(bench.filter(n=>!up.includes(n)))];if(!up.length)throw new Error("Put the starting players on the pitch first.");if(up.length>11)throw new Error("A starting lineup cannot have more than 11 players.");const old=await squad(id),oldMap=new Map(old.map(p=>[p.player,p])),pl=await players(true),meta=new Map(pl.map(p=>[p.name,p]));await db.begin(async tx=>{await tx.unsafe("delete from perranporth.player_match_data where match_id=$1",[id]);for(const pair of [...up.map(n=>[n,"Starter"]),...ub.map(n=>[n,"Sub"])]){const name=pair[0],status=pair[1],o=oldMap.get(name)||{},mt=meta.get(name)||{},st=status==="Starter";await tx.unsafe("insert into perranporth.player_match_data(match_id,player,squad_status,starter,starting_position,shirt_no,minute_on,minute_off,minutes_played,goals,assists,yellow_cards,red_cards,notes,raw_data) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,'{}'::jsonb)",[id,name,status,st,o.position||mt.position||"",o.shirtNo||mt.shirtNo||"",st?0:null,o.minuteOff===""?null:o.minuteOff??null,num(o.minutesPlayed),int(o.goals),int(o.assists),int(o.yellows),int(o.reds),norm(o.notes)]);}});if(payload)await saveLineup(id,payload);return summary(id);}
async function spectator(){const live=await q("select * from perranporth.matches where lower(status)='live' order by match_date desc nulls last,source_row desc nulls last limit 1");if(!live.length)return{live:false,generatedAt:new Date().toLocaleString("en-GB",{timeZone:"Europe/London"})};const m=live[0],id=String(m.match_id),ev=await events(id),sc=score(ev),cl=await clock(id),sq=await squad(id),li=await lineup(id),on=new Set(sq.filter(p=>p.status==="Starter"||p.starter).map(p=>p.player));for(const e of ev){if(e.type==="Substitution"){if(e.player)on.delete(e.player);if(e.secondaryPlayer)on.add(e.secondaryPlayer);}if(e.type==="Red Card"&&e.player)on.delete(e.player);}const red=new Set(ev.filter(e=>e.type==="Red Card"&&e.player).map(e=>e.player)),all=sq.filter(p=>p.status==="Starter"||p.status==="Sub").map(p=>p.player),pm=new Map(li.positions.map(p=>[p.player,p])),home=low(m.venue)!=="away";return{live:true,match:{matchId:id,date:dateText(m.match_date),kickoff:timeText(m.kickoff),opponent:norm(m.opponent),venue:norm(m.venue),competition:norm(m.competition),formation:li.formation||norm(m.formation)},homeTeam:home?"Perranporth":norm(m.opponent),awayTeam:home?norm(m.opponent):"Perranporth",homeScore:home?sc.ours:sc.opp,awayScore:home?sc.opp:sc.ours,clock:cl,onPitch:[...on].map(name=>{const p=pm.get(name);return{name,x:p?num(p.x):0,y:p?num(p.y):0,order:p?int(p.order):0};}),available:all.filter(p=>!on.has(p)&&!red.has(p)),dismissed:all.filter(p=>red.has(p)),events:ev.map(e=>({minute:e.minute,type:e.type,team:e.team,player:e.player,secondaryPlayer:e.secondaryPlayer,goalType:e.goalType,cardReason:e.cardReason})),generatedAt:new Date().toLocaleString("en-GB",{timeZone:"Europe/London"})};}

async function initData(){
  return {teamName:norm(await setting("Team Name"))||"Perranporth AFC",season:norm(await setting("Season"))||"2026/27",badgeUrl:norm(await setting("Voting Badge URL")),players:await players(true),allPlayers:await allPlayers(),matches:await matches(true)};
}
async function allPlayers(){
  const r=await q("select * from perranporth.players order by active desc,player asc");
  return r.map(x=>({name:norm(x.player),active:!!x.active,position:norm(x.default_position),shirtNo:x.shirt_no??"",goalkeeper:!!x.goalkeeper,notes:norm(x.notes),alias:norm(x.voting_alias),dateOfBirth:x.date_of_birth?String(x.date_of_birth):""})).filter(x=>x.name);
}
async function addPlayer(data){
  const name=norm(data?.name);if(!name)throw new Error("Enter a player name.");
  if((await q("select 1 from perranporth.players where lower(player)=lower($1) limit 1",[name])).length)throw new Error("That player already exists.");
  await q("insert into perranporth.players(player,active,default_position,shirt_no,goalkeeper,notes,voting_alias,portal_pin,pin_chosen,date_of_birth,raw_data) values($1,true,$2,$3,$4,$5,$6,'',false,$7,'{}'::jsonb)",[name,norm(data.position),norm(data.shirtNo),!!data.goalkeeper,norm(data.notes),norm(data.alias),data.dateOfBirth||null]);
  return{name,active:true,position:norm(data.position),shirtNo:norm(data.shirtNo),goalkeeper:!!data.goalkeeper,notes:norm(data.notes),alias:norm(data.alias)};
}
async function updatePlayer(originalName,data){
  const original=norm(originalName),name=norm(data?.name);if(!original)throw new Error("Player not found.");if(!name)throw new Error("Player name cannot be blank.");
  if((await q("select player from perranporth.players where lower(player)=lower($1) and lower(player)<>lower($2) limit 1",[name,original])).length)throw new Error("Another player already has that name.");
  const r=await q("update perranporth.players set player=$1,active=$2,default_position=$3,shirt_no=$4,goalkeeper=$5,notes=$6,voting_alias=$7,date_of_birth=$8 where lower(player)=lower($9) returning player",[name,data.active!==false,norm(data.position),norm(data.shirtNo),!!data.goalkeeper,norm(data.notes),norm(data.alias),data.dateOfBirth||null,original]);
  if(!r.length)throw new Error("Player not found.");
  if(low(original)!==low(name)){await q("update perranporth.player_match_data set player=$1 where lower(player)=lower($2)",[name,original]);await q("update perranporth.lineup_positions set player=$1 where lower(player)=lower($2)",[name,original]);await q("update perranporth.events set player=$1 where lower(player)=lower($2)",[name,original]);await q("update perranporth.events set secondary_player=$1 where lower(secondary_player)=lower($2)",[name,original]);}
  return{name,active:data.active!==false,position:norm(data.position),shirtNo:norm(data.shirtNo),goalkeeper:!!data.goalkeeper,notes:norm(data.notes),alias:norm(data.alias)};
}
async function seasonStats(){
  const r=await q("select p.player,p.squad_status,p.minutes_played,p.goals,p.assists,p.yellow_cards,p.red_cards from perranporth.player_match_data p join perranporth.matches m on m.match_id=p.match_id where m.status='Completed'");
  const map=new Map();for(const x of r){const name=norm(x.player);if(!name)continue;if(!map.has(name))map.set(name,{player:name,appearances:0,goals:0,assists:0,minutes:0,yellows:0,reds:0});const z=map.get(name);if(norm(x.squad_status)!=="Unused")z.appearances++;z.minutes+=num(x.minutes_played);z.goals+=int(x.goals);z.assists+=int(x.assists);z.yellows+=int(x.yellow_cards);z.reds+=int(x.red_cards);}return[...map.values()].sort((a,b)=>b.goals-a.goals||b.assists-a.assists||b.minutes-a.minutes||a.player.localeCompare(b.player));
}
async function minutesData(){
  const r=await q("select p.*,m.match_date,m.opponent,m.venue,m.competition from perranporth.player_match_data p join perranporth.matches m on m.match_id=p.match_id where m.status='Completed' order by m.match_date desc,p.player");
  const sm=new Map(),mm=new Map();for(const x of r){const player=norm(x.player),status=norm(x.squad_status),appeared=status!=="Unused"&&status!=="Not in Squad",starter=!!x.starter;if(!sm.has(player))sm.set(player,{player,starts:0,subApps:0,appearances:0,minutes:0});const s=sm.get(player);if(appeared){s.appearances++;if(starter)s.starts++;else s.subApps++;}s.minutes+=num(x.minutes_played);const id=String(x.match_id);if(!mm.has(id))mm.set(id,{matchId:id,date:dateText(x.match_date),opponent:norm(x.opponent),venue:norm(x.venue),competition:norm(x.competition),players:[]});mm.get(id).players.push({player,status,starter,minuteOn:x.minute_on??"",minuteOff:x.minute_off??"",minutesPlayed:num(x.minutes_played)});}const season=[...sm.values()].map(x=>({...x,averageMinutes:x.appearances?Math.round((x.minutes/x.appearances)*10)/10:0})).sort((a,b)=>b.minutes-a.minutes||b.appearances-a.appearances||a.player.localeCompare(b.player));return{season,matches:[...mm.values()]};
}
async function handle(action,args){
  if(action==="createAdminSession")return createSession(args[0]);
  if(action==="verifyPin")return !!(await ctx(args[0]));
  if(action==="logoutAdminSession"){await q("delete from perranporth.admin_sessions where token=$1",[norm(args[0])]);return true;}
  if(action==="getPublicSpectatorData")return spectator();
  const actionPerm=(action==="getInitData"||action==="getMatches"||action==="getSeasonStats"||action==="getPlayerMinutesData")?"read":(action==="getAllPlayersForAdmin"||action==="addPlayer"||action==="updatePlayer")?"*":"match";
  await auth(args[0],actionPerm);
  if(action==="getInitData")return initData();
  if(action==="getMatches")return matches(args[1]!==false);
  if(action==="getAllPlayersForAdmin")return allPlayers();
  if(action==="addPlayer")return addPlayer(args[1]||{});
  if(action==="updatePlayer")return updatePlayer(args[1],args[2]||{});
  if(action==="getSeasonStats")return seasonStats();
  if(action==="getPlayerMinutesData")return minutesData();
  if(action==="getSquad")return squad(norm(args[1]));
  if(action==="getLineup")return lineup(norm(args[1]));
  if(action==="getMatchSummary"||action==="getFullMatchSummary")return summary(norm(args[1]));
  if(action==="getMatchClock")return clock(norm(args[1]));
  if(action==="createMatch"){const d=args[1]||{},id="M"+new Date().toISOString().replace(/\D/g,"").slice(0,14);await q("insert into perranporth.matches(match_id,match_date,opponent,venue,competition,kickoff,status,formation,captain,notes,include,source,raw_data) values($1,$2,$3,$4,$5,$6,'Scheduled',$7,$8,$9,true,'Manual','{}'::jsonb)",[id,d.date||new Date().toISOString().slice(0,10),norm(d.opponent),norm(d.venue)||"Home",norm(d.competition)||"Other",d.kickoff||null,norm(d.formation),norm(d.captain),norm(d.notes)]);return id;}
  if(action==="createTrialMatch"){const tr=await q("select match_id from perranporth.matches where lower(source)='trial'");for(const t of tr){const id=String(t.match_id);await db.begin(async tx=>{for(const table of ["events","player_match_data","lineup_positions","votes","match_clocks"])await tx.unsafe("delete from perranporth."+table+" where match_id=$1",[id]);await tx.unsafe("delete from perranporth.matches where match_id=$1",[id]);});}const d=new Date(),id="TRIAL-"+new Intl.DateTimeFormat("sv-SE",{timeZone:"Europe/London",year:"numeric",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit",second:"2-digit"}).format(d).replace(/\D/g,"").replace(/^(\d{8})(\d{6}).*/,"$1-$2");await q("insert into perranporth.matches(match_id,match_date,opponent,venue,competition,kickoff,status,notes,include,source,raw_data) values($1,$2,'Demo / Trial Match','Home','Trial',$3,'Scheduled','Temporary demo match — excluded from real match lists and season data.',true,'Trial','{}'::jsonb)",[id,new Intl.DateTimeFormat("en-CA",{timeZone:"Europe/London"}).format(d),timeText(d)]);return id;}
  if(action==="deleteTrialMatch"){const id=norm(args[1]),m=await matchRow(id);if(low(m.source)!=="trial")throw new Error("Only trial matches can be deleted with this button.");await db.begin(async tx=>{for(const table of ["events","player_match_data","lineup_positions","votes","match_clocks"])await tx.unsafe("delete from perranporth."+table+" where match_id=$1",[id]);await tx.unsafe("delete from perranporth.matches where match_id=$1",[id]);});return true;}
  if(action==="saveSquad")return saveSquad(norm(args[1]),args[2]||[]);
  if(action==="addPlayerToLiveSquad"){const id=norm(args[1]),name=norm(args[2]),m=await matchRow(id);if(m.status!=="Live")throw new Error("Players can only be added this way while the match is live.");const p=(await players(true)).find(x=>x.name===name);if(!p)throw new Error("That player is not currently active in Manage Players.");const sq=await squad(id);if(!sq.length)throw new Error("No squad is saved for this match. All active players are already available for events.");if(sq.some(x=>x.player===name))return summary(id);await q("insert into perranporth.player_match_data(match_id,player,squad_status,starter,starting_position,shirt_no,minutes_played,goals,assists,yellow_cards,red_cards,notes,raw_data) values($1,$2,'Sub',false,$3,$4,0,0,0,0,0,'','{}'::jsonb)",[id,name,p.position,p.shirtNo]);return summary(id);}
  if(action==="saveLineup")return saveLineup(norm(args[1]),args[2]||{});
  if(action==="setStartingLineup")return starting(norm(args[1]),args[2]||{});
  if(action==="startMatch"){const id=norm(args[1]),m=await matchRow(id);if(m.status==="Completed")throw new Error("This match has already been completed.");if(m.status!=="Live"){await q("update perranporth.matches set status='Live' where match_id=$1",[id]);const n=Date.now();await writeClock({...defClock(id),startedAt:n,runningSince:n});}return summary(id);}
  if(action==="toggleMatchClock"){const id=norm(args[1]);await notDone(id);let c=await rawClock(id);if(!c.startedAt){const n=Date.now();c={...defClock(id),startedAt:n,runningSince:n};}else{if(c.onBreak)throw new Error("Start the second half using the Half Time button.");if(c.runningSince){c.baseSeconds=elapsed(c);c.runningSince=null;}else c.runningSince=Date.now();}return pubClock(await writeClock(c));}
  if(action==="resetMatchClock"){const id=norm(args[1]);await notDone(id);return pubClock(await writeClock(defClock(id)));}
  if(action==="enterHalfTime"){const id=norm(args[1]);await notDone(id);let c=await rawClock(id);if(!c.startedAt)throw new Error("The match clock has not been started.");const e=elapsed(c);c.baseSeconds=e;c.runningSince=null;c.onBreak=true;c.half=1;c.firstHalfAddedMinutes=e<=2700?0:Math.max(0,Math.floor((e-2700)/60)+1);return pubClock(await writeClock(c));}
  if(action==="startSecondHalf"){const id=norm(args[1]);await notDone(id);let c=await rawClock(id);if(!c.startedAt)throw new Error("The match clock has not been started.");if(!c.onBreak)throw new Error("The match is not currently at half time.");c.half=2;c.baseSeconds=2700;c.runningSince=Date.now();c.onBreak=false;return pubClock(await writeClock(c));}
  if(action==="logEvent"){const e=args[1]||args[2];await notDone(e.matchId);await validEvent(e);const id="E"+crypto.randomUUID().replace(/-/g,"").slice(0,12);await q("insert into perranporth.events(event_id,match_id,minute,event_type,team,player,secondary_player,goal_type,touches,goal_zone,assist_zone,card_reason,notes,event_timestamp,raw_data) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,now(),'{}'::jsonb)",[id,e.matchId,num(e.minute),norm(e.eventType),norm(e.team),norm(e.player),norm(e.secondaryPlayer),norm(e.goalType||e.restartPhase),e.touches===""?null:int(e.touches),norm(e.zone),norm(e.originZone),norm(e.cardReason),norm(e.notes)]);return summary(e.matchId);}
  if(action==="updateEvent"){const e=args[1]||args[2];await validEvent(e);const r=await q("update perranporth.events set minute=$1,event_type=$2,team=$3,player=$4,secondary_player=$5,goal_type=$6,touches=$7,goal_zone=$8,assist_zone=$9,card_reason=$10,notes=$11 where event_id=$12 and match_id=$13 returning event_id",[num(e.minute),norm(e.eventType),norm(e.team),norm(e.player),norm(e.secondaryPlayer),norm(e.goalType||e.restartPhase),e.touches===""?null:int(e.touches),norm(e.zone),norm(e.originZone),norm(e.cardReason),norm(e.notes),norm(e.eventId),norm(e.matchId)]);if(!r.length)throw new Error("Event not found.");await refreshStats(norm(e.matchId));return summary(norm(e.matchId));}
  if(action==="deleteEvent"){const eid=norm(args[1]),id=norm(args[2]),r=await q("delete from perranporth.events where event_id=$1 and match_id=$2 returning event_id",[eid,id]);if(!r.length)throw new Error("Event not found.");await refreshStats(id);return summary(id);}
  if(action==="deleteLastEvent"){const id=norm(args[1]);await notDone(id);const r=await q("select event_id from perranporth.events where match_id=$1 order by event_timestamp desc nulls last,id desc limit 1",[id]);if(r.length)await q("delete from perranporth.events where event_id=$1",[r[0].event_id]);return summary(id);}
  if(action==="finishMatch"){const id=norm(args[1]);await notDone(id);const ev=await events(id),sc=score(ev),snap=await clock(id);await q("update perranporth.matches set status='Completed',our_score=$1,opp_score=$2 where match_id=$3",[sc.ours,sc.opp,id]);let c=await rawClock(id),n=Date.now();c.baseSeconds=elapsed(c,n);c.runningSince=null;c.onBreak=false;c.finishedAt=n;await writeClock(c);await recalc(id,snap);return summary(id);}
  if(action==="reopenMatch"){const id=norm(args[1]),m=await matchRow(id);if(m.status!=="Completed")throw new Error("Only a completed match can be reopened.");await q("update perranporth.matches set status='Live' where match_id=$1",[id]);let c=await rawClock(id);c.finishedAt=null;c.onBreak=false;c.runningSince=null;await writeClock(c);return summary(id);}
  throw new Error("Unsupported Perranporth Supabase action: "+action);
}
Deno.serve(async req=>{if(req.method==="OPTIONS")return new Response("ok",{headers:CORS});if(req.method!=="POST")return fail("Method not allowed",405);try{const b=await req.json();return out(await handle(norm(b.action),Array.isArray(b.args)?b.args:[]));}catch(e){return fail(e instanceof Error?e.message:String(e),400);}});
